spring:
  application:
    name: cex-gateway
server:
    port: 8888
        
logging:
  level:
    # 框架日志
    '[org.springframework.cloud.gateway]': DEBUG        # Gateway 路由/过滤器日志
    '[org.springframework.web.reactive]': DEBUG         # WebFlux 请求日志
    '[reactor.netty.http.client]': DEBUG                # Netty 客户端（下游调用）
    '[org.springframework.cloud.loadbalancer]': INFO    # 负载均衡日志
    '[org.springframework.web.reactive.handler.RoutePredicateHandlerMapping]': TRACE

    # 自定义包日志
    #'[com.yourcompany.gateway.filter]': DEBUG           # 你的认证过滤器

  # 日志文件输出（可选）
  file:
    name: logs/gateway.log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] - %msg [%thread %-5level %logger{36}]%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}] - %msg [%thread %-5level %logger{36}]%n"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"